import Navbar from "@/app/Navbar";

// Metadata para la web, se transforma automaticamente a html
export const metadata = {
  title: "Holi",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
